#The Config file for LightingFixer
#Put in the materials you want to update
#Material list (CaSe-SeNsItIvE!) https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
materials:
  - BEACON
  - GLOWSTONE
  - JACK_O_LANTERN
  - REDSTONE_LAMP
  - SEA_LANTERN
  - TORCH
  - REDSTONE_TORCH
  - ENDER_CHEST
  - MAGMA_BLOCK
  - BREWING_STAND
  - DRAGON_EGG