name: LightingFixer
version: 1.0
description: Fixing lighting issues
author: boaler
main: me.boaler.lightingfixer.LightingFixer
api-version: 1.16

commands:
  fixlighting:
    description: Fixes lighting

permissions:
  fixlighting:
    description: Gives access to /fixlighting
    default: op